language: node_js
node_js:
  - "0.10"
  - "0.11"
before_install:
  - rvm use 1.9.3
install:
  - npm install -g grunt-cli
  - npm install
  - gem install --no-document jekyll kramdown
matrix:
  allow_failures:
    - node_js: "0.11"
