sudo: required

dist: trusty

language: node_js

node_js:
  - "4"

env:
  matrix:
    - RUBY_VERSION=2.2

before_install:
  # Remove ./node_modules/.bin from PATH so node-which doesn't replace Unix which and cause RVM to barf. See https://github.com/travis-ci/travis-ci/issues/5092
  - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))' "$PATH")
  - rvm install $RUBY_VERSION
  - rvm use $RUBY_VERSION --fuzzy

install:
  - npm install
  # Bundler downgrade should be removed when the issue is fixed upstream
  - gem uninstall bundler -x
  - gem install bundler -v "=1.10.6" --no-document
  - bundle install --retry 3 --clean --deployment

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules
    - vendor/bundle
